import Head from 'next/head'
import NavBar from '../components/NavBar'
import '../styles/globals.css'



function MyApp({ Component, pageProps }) {

  return ( <>
  <Head>
        <title>응애</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/egg.ico" />
      </Head>
  <NavBar />
  <Component {...pageProps} />

  </>
  )
}

export default MyApp
