import Head from 'next/head'
import styled, { keyframes  } from 'styled-components'
import styles from '../styles/Home.module.css'

const StringDiv = styled.div`
    position: relative;
    top: 30vh;
    display: flex;
    text-align: center;
    color: #fff;
    word-break: break-word;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    flex-wrap: nowrap;
    align-items: center;

    p {
      font-family: 'Raleway', 'Nanum Gothic';
      font-size: 50px;
      font-weight: bold;
      line-height: 1.3;
    }
`
const LikeNavDiv = styled.div`
    background-color: #0d51ff;
    background-image: none;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    width: 100vw;
    height: 100vh;
`
const PP = styled.p`
font-size: ${(props) => props.h3 ? props.h3 : "15px"};
padding-bottom : 10px;
`
const FontSpan = styled.span`
margin-right: 15vw;
`

const animation = keyframes`
  0%{
    background-color: white;
  }
  100%{
    background-color: #0d51ff;;
  }
`

const WhiteP = styled.p`
  
  box-sizing: content-box;
  color : #0d51ff;
  padding-left: 20px;
  position: relative;
  right: 10px;

  animation : ${animation} 1s linear infinite;
`


export default function Home() {
  return (
    <div>
      <Head>
        <title>응애</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/egg.ico" />
      </Head>
      <LikeNavDiv>
        <StringDiv>
          <p>Growing<FontSpan><br></br>
          developer
          </FontSpan></p>
          <WhiteP>Growing</WhiteP>
        </StringDiv>
      </LikeNavDiv>
    </div>
  )
}
